export declare const CRUDDABLE_DATA: {
    readonly APARTMENT: "apartments";
    readonly REVIEW: "reviews";
    readonly AMENITIE: "amenities";
    readonly APARTMENT_IMAGE: "apartment-images";
    readonly APARTMENT_BED: "apartment-beds";
    readonly APARTMENT_AMENITY: "apartment-amenities";
    readonly BED_TYPE: "bed-types";
    readonly EVENT: "events";
    readonly EVENT_IMAGE: "event-images";
    readonly ADDITIONAL_OPTION: "additional-options";
    readonly BOOKING_VARIANT: "booking-variants";
    readonly RESERVATION: "reservations";
    readonly BOOKING: "bookings";
    readonly TRANSACTION: "transactions";
    readonly TRANSFER_DETAIL: "transfer-details";
    readonly CARD_DETAIL: "card-details";
    readonly BOOKING_EVENT: "booking-events";
    readonly BOOKING_ADDITIONAL_OPTION: "booking-additional-options";
};
export type CRUDDABLE_NAMES = keyof typeof CRUDDABLE_DATA;
export type CRUDDABLE_PATHS = typeof CRUDDABLE_DATA[CRUDDABLE_NAMES];
export declare const GETTABLE_DATA: {
    readonly USER: "users";
    readonly SESSION: "sessions";
    readonly APARTMENT: "apartments";
    readonly REVIEW: "reviews";
    readonly AMENITIE: "amenities";
    readonly APARTMENT_IMAGE: "apartment-images";
    readonly APARTMENT_BED: "apartment-beds";
    readonly APARTMENT_AMENITY: "apartment-amenities";
    readonly BED_TYPE: "bed-types";
    readonly EVENT: "events";
    readonly EVENT_IMAGE: "event-images";
    readonly ADDITIONAL_OPTION: "additional-options";
    readonly BOOKING_VARIANT: "booking-variants";
    readonly RESERVATION: "reservations";
    readonly BOOKING: "bookings";
    readonly TRANSACTION: "transactions";
    readonly TRANSFER_DETAIL: "transfer-details";
    readonly CARD_DETAIL: "card-details";
    readonly BOOKING_EVENT: "booking-events";
    readonly BOOKING_ADDITIONAL_OPTION: "booking-additional-options";
};
export type GETTABLE_NAMES = keyof typeof GETTABLE_DATA;
export type GETTABLE_PATHS = typeof GETTABLE_DATA[GETTABLE_NAMES];
