import { BaseListResult } from "../../common";
import { ApartmentImage, BedType, Amenity, ApartmentAmenity, ApartmentBed, Review, Apartment } from "../../database";
import { ExtendedAmenity, ExtendedApartmentAmenity, ExtendedApartmentBed, ExtendedApartment, AvailableApartment, ApartmentAvailabilityResult } from "./extended.types";
export declare const example_apartment_amenity: ApartmentAmenity;
export declare const example_amenity: Amenity;
export declare const example_amenity_with_relations: ExtendedAmenity;
export declare const example_amenities_list_result: BaseListResult<ExtendedAmenity>;
export declare const example_extended_apartment_amenity: ExtendedApartmentAmenity;
export declare const example_extended_apartment_amenities_list_result: BaseListResult<ExtendedApartmentAmenity>;
export declare const example_bed_type: BedType;
export declare const example_bed_types_list_result: BaseListResult<BedType>;
export declare const example_apartment_bed: ApartmentBed;
export declare const example_extended_apartment_bed: ExtendedApartmentBed;
export declare const example_extended_apartment_beds_list_result: BaseListResult<ExtendedApartmentBed>;
export declare const example_apartment_image: ApartmentImage;
export declare const example_apartment_images_list_result: BaseListResult<ApartmentImage>;
export declare const example_apartment: Apartment;
export declare const example_available_apartment: AvailableApartment;
export declare const example_available_apartments_list_result: BaseListResult<AvailableApartment>;
export declare const example_apartment_availability_result: ApartmentAvailabilityResult;
export declare const example_review: Review;
export declare const example_extended_apartment: ExtendedApartment;
export declare const example_apartments_list_result: BaseListResult<AvailableApartment>;
export declare const example_reviews_list_result: BaseListResult<Review>;
